/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedlayoutRouteRouteImport } from './routes/(authenticated)/(layout)/route'
import { Route as authenticatedMatchMatchIdRouteImport } from './routes/(authenticated)/match/$matchId'
import { Route as authenticatedlayoutHomeRouteImport } from './routes/(authenticated)/(layout)/home'
import { Route as authenticatedlayoutProfileIndexRouteImport } from './routes/(authenticated)/(layout)/profile/index'
import { Route as authenticatedlayoutPlayIndexRouteImport } from './routes/(authenticated)/(layout)/play/index'
import { Route as authenticatedlayoutloginLoginRouteImport } from './routes/(authenticated)/(layout)/(login)/login'
import { Route as authenticatedlayoutProfileMatchesHistoryIndexRouteImport } from './routes/(authenticated)/(layout)/profile/matches-history/index'
import { Route as authenticatedlayoutProfileManageAccountIndexRouteImport } from './routes/(authenticated)/(layout)/profile/manage-account/index'
import { Route as authenticatedlayoutProfileMatchesHistoryRewindIdRouteImport } from './routes/(authenticated)/(layout)/profile/matches-history/$rewindId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedlayoutRouteRoute =
  authenticatedlayoutRouteRouteImport.update({
    id: '/(authenticated)/(layout)',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedMatchMatchIdRoute =
  authenticatedMatchMatchIdRouteImport.update({
    id: '/(authenticated)/match/$matchId',
    path: '/match/$matchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedlayoutHomeRoute = authenticatedlayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => authenticatedlayoutRouteRoute,
} as any)
const authenticatedlayoutProfileIndexRoute =
  authenticatedlayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => authenticatedlayoutRouteRoute,
  } as any)
const authenticatedlayoutPlayIndexRoute =
  authenticatedlayoutPlayIndexRouteImport.update({
    id: '/play/',
    path: '/play/',
    getParentRoute: () => authenticatedlayoutRouteRoute,
  } as any)
const authenticatedlayoutloginLoginRoute =
  authenticatedlayoutloginLoginRouteImport.update({
    id: '/(login)/login',
    path: '/login',
    getParentRoute: () => authenticatedlayoutRouteRoute,
  } as any)
const authenticatedlayoutProfileMatchesHistoryIndexRoute =
  authenticatedlayoutProfileMatchesHistoryIndexRouteImport.update({
    id: '/profile/matches-history/',
    path: '/profile/matches-history/',
    getParentRoute: () => authenticatedlayoutRouteRoute,
  } as any)
const authenticatedlayoutProfileManageAccountIndexRoute =
  authenticatedlayoutProfileManageAccountIndexRouteImport.update({
    id: '/profile/manage-account/',
    path: '/profile/manage-account/',
    getParentRoute: () => authenticatedlayoutRouteRoute,
  } as any)
const authenticatedlayoutProfileMatchesHistoryRewindIdRoute =
  authenticatedlayoutProfileMatchesHistoryRewindIdRouteImport.update({
    id: '/profile/matches-history/$rewindId',
    path: '/profile/matches-history/$rewindId',
    getParentRoute: () => authenticatedlayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof authenticatedlayoutHomeRoute
  '/match/$matchId': typeof authenticatedMatchMatchIdRoute
  '/login': typeof authenticatedlayoutloginLoginRoute
  '/play': typeof authenticatedlayoutPlayIndexRoute
  '/profile': typeof authenticatedlayoutProfileIndexRoute
  '/profile/matches-history/$rewindId': typeof authenticatedlayoutProfileMatchesHistoryRewindIdRoute
  '/profile/manage-account': typeof authenticatedlayoutProfileManageAccountIndexRoute
  '/profile/matches-history': typeof authenticatedlayoutProfileMatchesHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof authenticatedlayoutHomeRoute
  '/match/$matchId': typeof authenticatedMatchMatchIdRoute
  '/login': typeof authenticatedlayoutloginLoginRoute
  '/play': typeof authenticatedlayoutPlayIndexRoute
  '/profile': typeof authenticatedlayoutProfileIndexRoute
  '/profile/matches-history/$rewindId': typeof authenticatedlayoutProfileMatchesHistoryRewindIdRoute
  '/profile/manage-account': typeof authenticatedlayoutProfileManageAccountIndexRoute
  '/profile/matches-history': typeof authenticatedlayoutProfileMatchesHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)/(layout)': typeof authenticatedlayoutRouteRouteWithChildren
  '/(authenticated)/(layout)/home': typeof authenticatedlayoutHomeRoute
  '/(authenticated)/match/$matchId': typeof authenticatedMatchMatchIdRoute
  '/(authenticated)/(layout)/(login)/login': typeof authenticatedlayoutloginLoginRoute
  '/(authenticated)/(layout)/play/': typeof authenticatedlayoutPlayIndexRoute
  '/(authenticated)/(layout)/profile/': typeof authenticatedlayoutProfileIndexRoute
  '/(authenticated)/(layout)/profile/matches-history/$rewindId': typeof authenticatedlayoutProfileMatchesHistoryRewindIdRoute
  '/(authenticated)/(layout)/profile/manage-account/': typeof authenticatedlayoutProfileManageAccountIndexRoute
  '/(authenticated)/(layout)/profile/matches-history/': typeof authenticatedlayoutProfileMatchesHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/match/$matchId'
    | '/login'
    | '/play'
    | '/profile'
    | '/profile/matches-history/$rewindId'
    | '/profile/manage-account'
    | '/profile/matches-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/match/$matchId'
    | '/login'
    | '/play'
    | '/profile'
    | '/profile/matches-history/$rewindId'
    | '/profile/manage-account'
    | '/profile/matches-history'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)/(layout)'
    | '/(authenticated)/(layout)/home'
    | '/(authenticated)/match/$matchId'
    | '/(authenticated)/(layout)/(login)/login'
    | '/(authenticated)/(layout)/play/'
    | '/(authenticated)/(layout)/profile/'
    | '/(authenticated)/(layout)/profile/matches-history/$rewindId'
    | '/(authenticated)/(layout)/profile/manage-account/'
    | '/(authenticated)/(layout)/profile/matches-history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedlayoutRouteRoute: typeof authenticatedlayoutRouteRouteWithChildren
  authenticatedMatchMatchIdRoute: typeof authenticatedMatchMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/(layout)': {
      id: '/(authenticated)/(layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedlayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/match/$matchId': {
      id: '/(authenticated)/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof authenticatedMatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/(layout)/home': {
      id: '/(authenticated)/(layout)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authenticatedlayoutHomeRouteImport
      parentRoute: typeof authenticatedlayoutRouteRoute
    }
    '/(authenticated)/(layout)/profile/': {
      id: '/(authenticated)/(layout)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedlayoutProfileIndexRouteImport
      parentRoute: typeof authenticatedlayoutRouteRoute
    }
    '/(authenticated)/(layout)/play/': {
      id: '/(authenticated)/(layout)/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof authenticatedlayoutPlayIndexRouteImport
      parentRoute: typeof authenticatedlayoutRouteRoute
    }
    '/(authenticated)/(layout)/(login)/login': {
      id: '/(authenticated)/(layout)/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authenticatedlayoutloginLoginRouteImport
      parentRoute: typeof authenticatedlayoutRouteRoute
    }
    '/(authenticated)/(layout)/profile/matches-history/': {
      id: '/(authenticated)/(layout)/profile/matches-history/'
      path: '/profile/matches-history'
      fullPath: '/profile/matches-history'
      preLoaderRoute: typeof authenticatedlayoutProfileMatchesHistoryIndexRouteImport
      parentRoute: typeof authenticatedlayoutRouteRoute
    }
    '/(authenticated)/(layout)/profile/manage-account/': {
      id: '/(authenticated)/(layout)/profile/manage-account/'
      path: '/profile/manage-account'
      fullPath: '/profile/manage-account'
      preLoaderRoute: typeof authenticatedlayoutProfileManageAccountIndexRouteImport
      parentRoute: typeof authenticatedlayoutRouteRoute
    }
    '/(authenticated)/(layout)/profile/matches-history/$rewindId': {
      id: '/(authenticated)/(layout)/profile/matches-history/$rewindId'
      path: '/profile/matches-history/$rewindId'
      fullPath: '/profile/matches-history/$rewindId'
      preLoaderRoute: typeof authenticatedlayoutProfileMatchesHistoryRewindIdRouteImport
      parentRoute: typeof authenticatedlayoutRouteRoute
    }
  }
}

interface authenticatedlayoutRouteRouteChildren {
  authenticatedlayoutHomeRoute: typeof authenticatedlayoutHomeRoute
  authenticatedlayoutloginLoginRoute: typeof authenticatedlayoutloginLoginRoute
  authenticatedlayoutPlayIndexRoute: typeof authenticatedlayoutPlayIndexRoute
  authenticatedlayoutProfileIndexRoute: typeof authenticatedlayoutProfileIndexRoute
  authenticatedlayoutProfileMatchesHistoryRewindIdRoute: typeof authenticatedlayoutProfileMatchesHistoryRewindIdRoute
  authenticatedlayoutProfileManageAccountIndexRoute: typeof authenticatedlayoutProfileManageAccountIndexRoute
  authenticatedlayoutProfileMatchesHistoryIndexRoute: typeof authenticatedlayoutProfileMatchesHistoryIndexRoute
}

const authenticatedlayoutRouteRouteChildren: authenticatedlayoutRouteRouteChildren =
  {
    authenticatedlayoutHomeRoute: authenticatedlayoutHomeRoute,
    authenticatedlayoutloginLoginRoute: authenticatedlayoutloginLoginRoute,
    authenticatedlayoutPlayIndexRoute: authenticatedlayoutPlayIndexRoute,
    authenticatedlayoutProfileIndexRoute: authenticatedlayoutProfileIndexRoute,
    authenticatedlayoutProfileMatchesHistoryRewindIdRoute:
      authenticatedlayoutProfileMatchesHistoryRewindIdRoute,
    authenticatedlayoutProfileManageAccountIndexRoute:
      authenticatedlayoutProfileManageAccountIndexRoute,
    authenticatedlayoutProfileMatchesHistoryIndexRoute:
      authenticatedlayoutProfileMatchesHistoryIndexRoute,
  }

const authenticatedlayoutRouteRouteWithChildren =
  authenticatedlayoutRouteRoute._addFileChildren(
    authenticatedlayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedlayoutRouteRoute: authenticatedlayoutRouteRouteWithChildren,
  authenticatedMatchMatchIdRoute: authenticatedMatchMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
