/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as PlayRoleRouteImport } from './routes/play/$role'

const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoleRoute = PlayRoleRouteImport.update({
  id: '/play/$role',
  path: '/play/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/play/$role': typeof PlayRoleRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesByTo {
  '/play/$role': typeof PlayRoleRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/play/$role': typeof PlayRoleRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/play/$role' | '/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/play/$role' | '/play'
  id: '__root__' | '/play/$role' | '/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlayRoleRoute: typeof PlayRoleRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$role': {
      id: '/play/$role'
      path: '/play/$role'
      fullPath: '/play/$role'
      preLoaderRoute: typeof PlayRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PlayRoleRoute: PlayRoleRoute,
  PlayIndexRoute: PlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
